### ISSUE TITLE
Compilation of Synfigstudio fails when emerging Synfig -fontconfig

### ISSUE THREAD

**Issue by Mikrotherion** [ceamac/overlay#3]
Hello,
thanks for the overlay.
I noticed that Synfigstudio won't compile for me if I compile Synfig without the fontconfig use flag.
Adding the use flag fixed it.

**Comment by ceamac** [comment]
Thank you for noticing this and letting me know.

I fixed it by adding a `fontconfig` USE flag.  I also noticed it has experimental `jack` support, so I added a flag for that too.
